backend:
  name: git-gateway
  branch: main

locale: sl
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Blog zapis"
    folder: "content/blog"
    create: true
    delete: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    summary: "{{title}} – {{date}}"
    fields:
      - { label: "Naslov", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Kategorija", name: "category", widget: "string", default: "Razmišljanja" }
      - { label: "Kratek uvod", name: "excerpt", widget: "text", hint: "Ta tekst se pokaže na naslovnici in na seznamu blogov." }
      - { label: "Besedilo", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Strani"
    files:
      - label: "O meni"
        name: "about"
        file: "_data/about.json"
        fields:
          - { label: "Glavni naslov", name: "heading", widget: "string" }
          - { label: "Prvi odstavek", name: "paragraph1", widget: "text" }
          - { label: "Drugi odstavek", name: "paragraph2", widget: "text" }
          - { label: "Tretji odstavek", name: "paragraph3", widget: "text" }
      - label: "Naslovnica"
        name: "home"
        file: "_data/home.json"
        fields:
          - { label: "Naslovna slika", name: "heroImage", widget: "image" }
          - { label: "Opis slike", name: "heroAlt", widget: "string", required: false }
